spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/glody_db?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # hoặc validate, create, create-drop tùy mục đích
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

jwt:
  secret: secret-key-change-this
  expirationMs: 86400000
