spring:
  application:
    name: glody-platform

    mvc:
      view:
        prefix: classpath:/templates/
        suffix: .html
    thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false


  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/glody_db?useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
#  config:
#    import: optional:file:.env[.properties]

#server:
#  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/keystore.p12
#    key-store-password: ${SSL_KEYSTORE_PASSWORD:password}
#    key-store-type: PKCS12

jwt:
  secret: secret-key-change-this
  expirationMs: 86400000

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha

payos:
  client-id:    ${PAYOS_CLIENT_ID:757c90c4-63da-4d1f-8d70-041bee93be81}
  api-key:      ${PAYOS_API_KEY:0f7d0e96-672c-4698-9337-a122daf6aa1f}
  checksum-key: ${PAYOS_CHECKSUM_KEY:cc085211e7d008940e43cd45e807751c929fc1b34c403a396e037dbc56a28669}
  base-url:     https://api-merchant.payos.vn